    name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    name: Deploy to Hetzner
      run: |
        ssh user@your_server_ip << EOF
          cd /path/to/your/app
          git pull
          # Any other deployment commands
        EOF
