name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Hetzner
        run: |
          ssh root@91.107.196.114 << EOF
          cd /
          git pull
          # Any other deployment commands
          EOF
